<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>George Chloe Elohor's Dynamic Portfolio</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <img src="https://imgur.com/drgwCkz.png" alt="George Chloe Elohor Profile" id="profile-img" />
    <h1>Hello, I'm George Chloe Elohor!</h1>
    <p>Cyber Security Student | Passionate about web development and creating engaging experiences.</p>
  </header>

  <main>
    <section id="about">
      <h2>About Me</h2>
      <p>
        I am a student of Cyber Security (Matric No:24/14645)
      </p>
    </section>

    <section id="multimedia-showcase">
      <h2>Multimedia Showcase</h2>
      <h3>My Audio Greeting:</h3>
      <audio controls>
        <source src="https://voca.ro/1mbmsISvUsQD.mp3" type="audio/mpeg" />
        Your browser does not support the audio element.
      </audio>

      <h3>A Quick Project Video:</h3>
      <video controls width="320" height="240">
        <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
    </section>

    <section id="interactive-skills">
      <h2>My Skills</h2>
      <div class="skill-buttons">
        <button class="skill-btn" data-skill="HTML">HTML</button>
        <button class="skill-btn" data-skill="CSS">CSS</button>
        <button class="skill-btn" data-skill="JavaScript">JavaScript</button>
      </div>
      <p id="skill-description">Click a skill to learn more!</p>
    </section>

    <section id="portfolio-list">
      <h2>My Projects</h2>
      <div id="projects-container"></div>
    </section>
  </main>

  <footer>
    <p>&copy; <span id="current-year"></span> George Chloe Elohor. All rights reserved.</p>
    <button id="themeToggle">Toggle Dark Mode</button>
  </footer>

  <script>
    document.getElementById('current-year').textContent = new Date().getFullYear();

    const skillInfo = {
      HTML 
      CSS
      JavaScript 
    };

    document.querySelectorAll('.skill-btn').forEach((btn) => {
      btn.addEventListener('click', () => {
        const skill = btn.dataset.skill;
        const desc = document.getElementById('skill-description');
        desc.textContent = skillInfo[skill];
        desc.style.color = '#0056b3';
      });
    });

    const toggleBtn = document.getElementById('themeToggle');
    toggleBtn.addEventListener('click', () => {
      document.body.classList.toggle('dark-mode');
      localStorage.setItem('theme', document.body.classList.contains('dark-mode') 

    if (localStorage.getItem('theme') === 'dark') {
      document.body.classList.add('dark-mode');
    }

    async function loadProjects() {
      const container = document.getElementById('projects-container');
      try {
        const res = await fetch('data/portfolio_items.json');
        const data = await res.json();
        data.forEach((project) => {
          const div = document.createElement('div');
          div.className = 'project-card';
          div.innerHTML = `<h3>${project.name}</h3><p>${project.description}</p><a href="${project.link}" target="_blank">View Project</a>`;
          container.appendChild(div);
        });
      } catch (e) {
        container.innerHTML = '<p>Failed to load projects.</p>';
      }
    }
    loadProjects();
  </script>
</body>
</html>
body {
    font-family
    margin
    background-color
    color
    line-height
    
}

body.dark-mode {
    background-color
    color:
}

header {
    background-color: #007bff;
    color: white;
    padding: 20px 0;
    text-align: center;
    box-shadow: 0 4px 8px rgba(0,0,0,0.2);
}

header img {
    border-radius: 50%;
    border: 4px solid white;
    margin-bottom: 10px;
    width: 120px;
    height: 120px;
    object-fit: cover;
}

main {
    max-width: 900px;
    margin: 20px auto;
    padding: 0 20px;
}

section {
    background-color: white;
    padding: 25px;
    margin-bottom: 25px;
    border-radius: 10px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    transition: background-color 0.3s ease, box-shadow 0.3s ease;
}

body.dark-mode section {
    background-color: #333;
    box-shadow: 0 2px 5px rgba(0,0,0,0.3);
}

h1, h2, h3 {
    color: #0056b3;
}

body.dark-mode h1,
body.dark-mode h2,
body.dark-mode h3 {
    color: #87ceeb;
}

.skill-buttons {
    display: flex;
    justify-content: center;
    gap: 10px;
    margin-top: 20px;
}

.skill-btn {
    background-color: #28a745;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 1em;
    transition: background-color 0.3s ease, transform 0.2s ease;
}

.skill-btn:hover {
    background-color: #218838;
    transform: translateY(-2px);
}

#skill-description {
    margin-top: 15px;
    font-style: italic;
    min-height: 20px;
}

footer {
    text-align: center;
    padding: 20px;
    background-color: #007bff;
    color: white;
    position: relative;
    bottom: 0;
    width: 100%;
    box-shadow: 0 -2px 8px rgba(0,0,0,0.2);
}

#themeToggle {
    background-color: #ffc107;
    color: #333;
    padding: 8px 15px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-top: 10px;
    transition: background-color 0.3s ease;
}

#themeToggle:hover {
    background-color: #e0a800;
}

.project-card {
    border: 1px solid #ddd;
    padding: 15px;
    margin-bottom: 15px;
    border-radius: 8px;
    background-color: #f9f9f9;
    text-align: left;
    transition: transform 0.2s ease, background-color 0.3s ease;
}

body.dark-mode .project-card {
    background-color: #444;
    border-color: #555;
}

.project-card:hover {
    transform: translateY(-3px);
    box-shadow: 0 4px 8px rgba(0,0,0,0.15);
}

.project-card h3 {
    color: #007bff;
    margin-top: 0;
}

body.dark-mode .project-card h3 {
    color: #87ceeb;
}[
  {
    "name": "My First HTML Page",
    "description": "A simple static page demonstrating basic HTML structure and elements.",
    "link": "#"
  },
  {
    "name": "CSS Styling Practice",
    "description": "Explored various CSS properties to style text, colors, and layout.",
    "link": "#"
  },
  {
    "name": "Interactive JavaScript Fun",
    "description": "Implemented basic JavaScript to add dynamic behavior and user interaction.",
    "link": "#"
  }
]
